abbr -a ll 'lsd -lh'
abbr -a la 'lsd -lah'
abbr -a cl 'clear'
abbr -a gpf 'git push --force-with-lease'
abbr -a gm 'git switch main'
abbr -a gs 'git switch'
abbr -a gc 'git checkout'
abbr -a gch 'git rev-parse HEAD'
abbr -a gsave 'git_quicksave'
abbr -a cg 'cd_ghq'
abbr -a gu 'gitui'
abbr -a ol 'ollama'
abbr -a sql 'lazysql'
abbr -a golint 'golangci-lint'
abbr -a gcloud-switch 'gcloud config configurations activate'
abbr -a swh 'sips -g pixelWidth -g pixelHeight'
abbr -a ls-img 'img2sixel'
abbr -a dc-exec 'docker container exec -it'
abbr -a dcon-exec 'devcontainer exec --workspace-folder . /bin/bash -i'
abbr -a gh-pr-me 'gh pr list --author "@me" --state all'
abbr -a git-tree "git log --graph --pretty=format:'%x09%C(auto) %h %Cgreen %cd %Creset%x09%C(cyan ul)%an%Creset %x09%C(auto)%s %d' --date=format:'%Y-%m-%d (%a)'"
abbr -a h 'history | fzf | pbcopy'
# カーソル位置指定あり（% の位置にカーソルが移動）
abbr -a psp --set-cursor 'ps -fp (lsof -t -i :%)'
abbr -a ghe --set-cursor 'gh copilot explain "%"'
abbr -a restore --set-cursor 'git checkout % -- .'
abbr -a gh-pr-search --set-cursor 'gh pr list --state all --json number,title --jq ".[] | [.number,.title] | @csv" --search "%" | fzf | awk -F \',\' \'{print $1}\' | xargs gh browse'
