[vars]
dotfiles_purpose = "work"

[tools]
awscli = "latest"
lazydocker = "latest"
yarn = "4"
gcloud = "latest"
stripe = "latest"
# bin/ に llmman も同梱される
"github:docker/sbx-releases" = { version = "latest", asset_pattern = "DockerSandboxes-darwin.tar.gz", filter_bins = "sbx" }
"go:github.com/laravel-ls/laravel-ls/cmd/laravel-ls" = "latest"
"npm:@ember-tooling/ember-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:aws-cdk" = "latest"
"pipx:awscli-local" = { version = "latest", extras = "ver1" }

[bootstrap.packages]
"brew-cask:figma" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:claude" = "latest"
"brew-cask:cursor" = "latest"
"brew-cask:docker-desktop" = "latest"
