## Everforest Dark (Soft)
set-option -g status "on"
set-option -g status-style bg=#343f44,fg=#d3c6aa
set-window-option -g window-status-style bg=#a7c080,fg=#343f44
set-window-option -g window-status-activity-style bg=#343f44,fg=#9da9a0
set-window-option -g window-status-current-style bg=#e69875,fg=#343f44
set-option -g pane-active-border-style fg=#a7c080
set-option -g pane-border-style fg=#475258
set-option -g message-style bg=#3d484d,fg=#d3c6aa
set-option -g message-command-style bg=#3d484d,fg=#d3c6aa
set-option -g display-panes-active-colour "#a7c080"
set-option -g display-panes-colour "#475258"
set-window-option -g clock-mode-colour "#7fbbb3"
set-window-option -g window-status-bell-style bg=#e67e80,fg=#2d353b
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right ""
set-window-option -g window-status-separator ""
set-option -g status-left "#[bg=#475258,fg=#d3c6aa] #S #[bg=#343f44,fg=#475258,nobold,noitalics,nounderscore]"
set-window-option -g window-status-current-format "#[bg=#a7c080,fg=#343f44,nobold,noitalics,nounderscore]#[bg=#a7c080,fg=#2d353b] #I #[bg=#a7c080,fg=#2d353b,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#343f44,fg=#a7c080,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#3d484d,fg=#343f44,noitalics]#[bg=#3d484d,fg=#d3c6aa] #I #[bg=#3d484d,fg=#d3c6aa] #W #[bg=#343f44,fg=#3d484d,noitalics]"
