## Everforest Light (Soft)
set-option -g status "on"
set-option -g status-style bg=#e5e0d8,fg=#5c6a72
set-window-option -g window-status-style bg=#8da101,fg=#e5e0d8
set-window-option -g window-status-activity-style bg=#e5e0d8,fg=#859289
set-window-option -g window-status-current-style bg=#f57d26,fg=#f3efe4
set-option -g pane-active-border-style fg=#8da101
set-option -g pane-border-style fg=#d4cfc8
set-option -g message-style bg=#d4cfc8,fg=#5c6a72
set-option -g message-command-style bg=#d4cfc8,fg=#5c6a72
set-option -g display-panes-active-colour "#8da101"
set-option -g display-panes-colour "#d4cfc8"
set-window-option -g clock-mode-colour "#3a94c5"
set-window-option -g window-status-bell-style bg=#f85552,fg=#f3efe4
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right ""
set-window-option -g window-status-separator ""
set-option -g status-left "#[bg=#c9c4bd,fg=#5c6a72] #S #[bg=#e5e0d8,fg=#c9c4bd,nobold,noitalics,nounderscore]"
set-window-option -g window-status-current-format "#[bg=#8da101,fg=#e5e0d8,nobold,noitalics,nounderscore]#[bg=#8da101,fg=#f3efe4] #I #[bg=#8da101,fg=#f3efe4,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#e5e0d8,fg=#8da101,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#f0ebe4,fg=#e5e0d8,noitalics]#[bg=#f0ebe4,fg=#5c6a72] #I #[bg=#f0ebe4,fg=#5c6a72] #W #[bg=#e5e0d8,fg=#f0ebe4,noitalics]"
