onboarding = false
[keys]
prefix = "ctrl+space"
new_tab = "prefix+c"
rename_tab = "prefix+comma"
previous_tab = "prefix+["
next_tab = "prefix+]"

[ui]
prompt_new_tab_name = false
agent_panel_sort = "priority"

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"
delay_seconds = 1

[ui.toast.herdr]
position = "top-right"

[ui.toast.clipboard]
enabled = true
position = "bottom-center"

[experimental]
pane_history = true
